# Generated by Django 2.2.16 on 2020-09-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feture_name', models.CharField(max_length=128)),
            ],
        ),
    ]
